Buildroot:      @CPACK_TARGET_RPM_DIR@/@CPACK_PACKAGE_FILE_NAME@
Summary:        FOEDUS-CORE: Fast Optimistic Engine for Data Unification Services Core Library
Name:           @CPACK_PACKAGE_NAME@
Version:        @CPACK_PACKAGE_VERSION@
Release:        @CPACK_PACKAGE_RELEASE@
License:        Other
Group:          Development/Tools/Other
Vendor:         @CPACK_PACKAGE_VENDOR@
Prefix:         @CPACK_PACKAGING_INSTALL_PREFIX@
# Requires:

%define _rpmdir @CPACK_TARGET_RPM_DIR@
%define _rpmfilename @CPACK_PACKAGE_FILE_NAME@.rpm
%define _unpackaged_files_terminate_build 0
%define _topdir @CPACK_TARGET_RPM_DIR@

%description
This library is the gut of FOEDUS as a transactional key-value storage system.
Any client program can link to it as a shared library.

# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
echo "[prep phase]"
mv $RPM_BUILD_ROOT @CPACK_TARGET_RPM_DIR@/tmpBBroot

%build
echo "[build phase]"
echo "RPM_BUILD_ROOT=$RPM_BUILD_ROOT"
make
make dox

%install
echo "[install phase]"
if [ -e $RPM_BUILD_ROOT ];
then
  rm -Rf $RPM_BUILD_ROOT
fi
mv "@CPACK_TARGET_RPM_DIR@/tmpBBroot" $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
@CPACK_PACKAGING_INSTALL_PREFIX@/@LIB_INSTALL_DIR@/*
@CPACK_PACKAGING_INSTALL_PREFIX@/bin/foedus
@CPACK_PACKAGING_INSTALL_PREFIX@/share/doc/foedus-core

%changelog
* Fri May 16 2014 Hideaki Kimura <hideaki.kimura@hp.com> 0.1.0
- Initial RPM Release
